# Site settings
title: Triyana Nurhidayah
description: 'Mahasiswa'
url: 'http://thomas.zuehlke.family'
baseurl: ''
profilepic: '/images/d.jpg'
bkimage: '/images/mat.jpg'
google_analytics: UA-XXXXXX-X
font_awesome: 'https://kit.fontawesome.com/{{ site.font_awesome }}'

author:
  name: 'Triyana Nurhidayah'
  email: triana.nurhidayah12@gmail.com
  twitter_username: triananrdyh
#  facebook_username: joshgerdes
  github_username:  triana12
  
# Build settings
destination: _site
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

#plugins: ['jekyll-paginate']
exclude: ['README.md', 'screenshot-overview.png']
